openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: A simple API for managing users
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  "/":
    get:
      summary: Home
      description: Returns a welcome message.
      responses:
        "200":
          description: Welcome message
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to the Express Server!
  "/users":
    get:
      summary: Get all users
      description: Fetches the list of all users.
      responses:
        "200":
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
  "/users/{id}":
    get:
      summary: Get user by ID
      description: Fetches a single user by their ID.
      parameters:
        - name: id
          in: path
          description: ID of the user to fetch
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Alice
        age:
          type: integer
          example: 25
      required:
        - id
        - name
        - age
